---
output: html_document
editor_options: 
  chunk_output_type: console
---

#0.0 Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
here <- here()
here
library(tidyverse)
library(lubridate)
library(fs)
library(xts)
library(dygraphs)
library(readxl)
library(scales)


#Load import function
source(paste0(here, "/src/hobo_import.R"))
#Load a table of constants to use in calculations below
const <- readRDS(paste0(here,"/data/TF_SF_const.Rds"))
```


#1.0 Import hobo records, convert to yields
```{r}

#SF-A-----
site <- "SF-A"
#get file paths
paths <- dir_ls(paste0(here, "/data/hobo/pressure_corrected/",
                       site, "/"))
#row bind results of import function
hobo <- map_dfr(paths, hobo_import)
#Calculate yields
hobo_2 <- hobo %>% 
  mutate(vol_L = depth_m*1000 * const$val[["SF_L_mm"]], #0.05 L/mm depth in bucket
         vol_mm3 = vol_L * 1E+6, #1000000mm^3/L
         yield_mm_hobo = vol_mm3/const$val[["SF_A_CA_mm2"]])  #water yield normalized to tree canopy area 

#plot
plot(hobo_2$yield_mm_hobo ~ hobo_2$dt)

dir_create(paste0(here, "/output/hobo_imported/", site))

#save imported hobo record
saveRDS(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
write_csv(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.csv"))

rm(hobo, hobo_2, site, paths)

#SF-B-----
site <- "SF-B"
#get file paths
paths <- dir_ls(paste0(here, "/data/hobo/pressure_corrected/",
                       site, "/"))
#row bind results of import function
hobo <- map_dfr(paths, hobo_import)
#Calculate yields
hobo_2 <- hobo %>% 
  mutate(vol_L = depth_m*1000 * const$val[["SF_L_mm"]], #0.05 L/mm depth in bucket
         vol_mm3 = vol_L * 1E+6, #1000000mm^3/L
         yield_mm_hobo = vol_mm3/const$val[["SF_B_CA_mm2"]],#water yield normalized to tree canopy area 
         yield_mm_hobo_zeroed = case_when(yield_mm_hobo < 0 ~ 0.0,
                                          TRUE ~ yield_mm_hobo))

hobo_3 <- hobo_2 %>% 
  mutate(dt_hr = round_date(dt, unit = "hour")) %>% 
  group_by(dt_hr) %>% 
  summarise(yield_mm_hobo_hr = sum(yield_mm_hobo_zeroed)) %>% 
  ungroup()

#plot
hobo_3_xts <- xts(hobo_3 %>% select(dt_hr, yield_mm_hobo_hr), order.by=hobo_3$dt_hr)
dygraph(hobo_3_xts) %>% #dyAxis("y", valueRange = c(-1, 1)) %>% 
  dyRangeSelector()
  

plot(hobo_2$yield_mm_hobo ~ hobo_2$dt)

dir_create(paste0(here, "/output/hobo_imported/", site))

#save imported hobo record
saveRDS(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
write_csv(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.csv"))

rm(hobo, hobo_2, site, paths)




#SF-C-----
site <- "SF-C"
#get file paths
paths <- dir_ls(paste0(here, "/data/hobo/pressure_corrected/",
                       site, "/"))
#row bind results of import function
hobo <- map_dfr(paths, hobo_import)
#Calculate yields
hobo_2 <- hobo %>% 
  mutate(vol_L = depth_m*1000 * const$val[["SF_L_mm"]], #0.05 L/mm depth in bucket
         vol_mm3 = vol_L * 1E+6, #1000000mm^3/L
         yield_mm_hobo = vol_mm3/const$val[["SF_C_CA_mm2"]])  #water yield normalized to tree canopy area 

#plot
plot(hobo_2$yield_mm_hobo ~ hobo_2$dt)

dir_create(paste0(here, "/output/hobo_imported/", site))

#save imported hobo record
saveRDS(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
write_csv(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.csv"))

rm(hobo, hobo_2, site, paths)




#SF-D-----
site <- "SF-D"
#get file paths
paths <- dir_ls(paste0(here, "/data/hobo/pressure_corrected/",
                       site, "/"))
#row bind results of import function
hobo <- map_dfr(paths, hobo_import)
#Calculate yields
hobo_2 <- hobo %>% 
  mutate(vol_L = depth_m*1000 * const$val[["SF_L_mm"]], #0.05 L/mm depth in bucket
         vol_mm3 = vol_L * 1E+6, #1000000mm^3/L
         yield_mm_hobo = vol_mm3/const$val[["SF_D_CA_mm2"]])  #water yield normalized to tree canopy area 

#plot
plot(hobo_2$yield_mm_hobo ~ hobo_2$dt)

dir_create(paste0(here, "/output/hobo_imported/", site))

#save imported hobo record
saveRDS(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
write_csv(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.csv"))

rm(hobo, hobo_2, site, paths)



#TF-B-----
site <- "TF-B"
#get file paths
paths <- dir_ls(paste0(here, "/data/hobo/pressure_corrected/",
                       site, "/"))
#row bind results of import function
hobo <- map_dfr(paths, hobo_import)
#Calculate yields
hobo_2 <- hobo %>% 
  mutate(vol_L = depth_m*1000 * const$val[["TF_L_mm"]], #0.09 L/mm depth in Trash bin
         vol_mm3 = vol_L * 1E+6, #1000000mm^3/L
         yield_mm_hobo = vol_mm3/const$val[["TFB_D_Area_mm2"]])  #water yield normalized to tree canopy area 

#plot
plot(hobo_2$yield_mm_hobo ~ hobo_2$dt)

dir_create(paste0(here, "/output/hobo_imported/", site))

#save imported hobo record
saveRDS(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
write_csv(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.csv"))

rm(hobo, hobo_2, site, paths)



#TF-D-----
site <- "TF-D"
#get file paths
paths <- dir_ls(paste0(here, "/data/hobo/pressure_corrected/",
                       site, "/"))
#row bind results of import function
hobo <- map_dfr(paths, hobo_import)
#Calculate yields
hobo_2 <- hobo %>% 
  mutate(vol_L = depth_m*1000 * const$val[["TF_L_mm"]], #0.09 L/mm depth in Trash bin
         vol_mm3 = vol_L * 1E+6, #1000000mm^3/L
         yield_mm_hobo = vol_mm3/const$val[["TFB_D_Area_mm2"]])  #water yield normalized to tree canopy area 

#plot
plot(hobo_2$yield_mm_hobo ~ hobo_2$dt)

dir_create(paste0(here, "/output/hobo_imported/", site))

#save imported hobo record
saveRDS(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
write_csv(hobo_2, paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.csv"))

rm(hobo, hobo_2, site, paths)

```

##1.1 Browse time series to select events manually
```{r}

site <- "SF-A"
hobo <- readRDS(paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
hobo2 <- hobo %>% select(dt, yield_mm_hobo)
hobo_xts <- xts(hobo2, order.by=hobo$dt)
dygraph(hobo_xts) %>% dyAxis("y", valueRange = c(-1, 1)) %>% 
  dyRangeSelector()
hobo_all <- hobo2 %>% rename("SFA_mm" = yield_mm_hobo)

site <- "SF-B"
hobo <- readRDS(paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
hobo2 <- hobo %>% select(dt, yield_mm_hobo)
hobo_xts <- xts(hobo2, order.by=hobo$dt)
dygraph(hobo_xts) %>% dyAxis("y", valueRange = c(-1, 1)) %>% 
  dyRangeSelector()
hobo_all <- hobo_all %>% full_join(., hobo2 %>% 
                                     rename("SFB_mm" = yield_mm_hobo),
                                   by = "dt")



site <- "SF-C"
hobo <- readRDS(paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
hobo2 <- hobo %>% select(dt, yield_mm_hobo)
hobo_xts <- xts(hobo2, order.by=hobo$dt)
dygraph(hobo_xts) %>% dyAxis("y", valueRange = c(-1, 1)) %>% 
  dyRangeSelector()
hobo_all <- hobo_all %>% full_join(., hobo2 %>% 
                                     rename("SFC_mm" = yield_mm_hobo),
                                   by = "dt")


site <- "SF-D"
hobo <- readRDS(paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
hobo2 <- hobo %>% select(dt, yield_mm_hobo)
hobo_xts <- xts(hobo2, order.by=hobo$dt)
dygraph(hobo_xts) %>% dyAxis("y", valueRange = c(-1, 1)) %>% 
  dyRangeSelector()
hobo_all <- hobo_all %>% full_join(., hobo2 %>% 
                                     rename("SFD_mm" = yield_mm_hobo),
                                   by = "dt")
site <- "TF-B"
hobo <- readRDS(paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
hobo2 <- hobo %>% select(dt, yield_mm_hobo)
hobo_xts <- xts(hobo2, order.by=hobo$dt)
dygraph(hobo_xts) %>% dyAxis("y", valueRange = c(-1, 1)) %>% 
  dyRangeSelector()
hobo_all <- hobo_all %>% full_join(., hobo2 %>% 
                                     rename("TFB_mm" = yield_mm_hobo),
                                   by = "dt")

site <- "TF-D"
hobo <- readRDS(paste0(here, "/output/hobo_imported/",
                       site, "/", site, "_imported.Rds"))
hobo2 <- hobo %>% select(dt, yield_mm_hobo)
hobo_xts <- xts(hobo2, order.by=hobo$dt)
dygraph(hobo_xts) %>% dyAxis("y", valueRange = c(-1, 1)) %>% 
  dyRangeSelector()
hobo_all <- hobo_all %>% full_join(., hobo2 %>% 
                                     rename("TFD_mm" = yield_mm_hobo),
                                   by = "dt")

#interactive plot of throughfall
hobo_all_xts <- xts(hobo_all %>% select(dt, TFB_mm, TFD_mm),
                    order.by=hobo_all$dt)
dygraph(hobo_all_xts) %>% dyAxis("y", valueRange = c(-1, 100)) %>% 
  dyRangeSelector() %>% dyOptions(useDataTimezone = TRUE)

#interactive plot of stemflow
hobo_all2_xts <- xts(hobo_all %>% select(dt, SFA_mm, SFB_mm, SFC_mm, SFD_mm),
                     order.by=hobo_all$dt)
dygraph(hobo_all2_xts) %>% dyAxis("y", valueRange = c(-0.1, 1)) %>% 
  dyRangeSelector() %>% dyOptions(useDataTimezone = TRUE)

saveRDS(hobo_all, paste0(here,"/output/hobo_compiled_wide.Rds"))

```


