---
output: html_document
editor_options: 
  chunk_output_type: console
---

#0.0 Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
here <- here()
here
library(tidyverse)
library(lubridate)
library(fs)
library(xts)
library(dygraphs)
library(readxl)
library(scales)


#Load import function
source(paste0(here, "/src/hobo_import.R"))
#Load a table of constants to use in calculations below
const <- readRDS(paste0(here,"/data/TF_SF_const.Rds"))
```



#2.0 Import selected event intervals
```{r}
#Import stemflow and throughfall time intervals
r2_events <- readxl::read_excel(paste0(here, "/data/hobo/hobo_events.xlsx"))
tz(r2_events$start_time_EST) #imported time zone is UTC

sapply(r2_events, class)
r2_events2 <- r2_events %>% 
  mutate(across(.cols = lubridate::is.POSIXct,
                ~ lubridate::force_tz(., tzone='EST'))) %>% 
  mutate(.after = end_time_EST,
         datetime_interval_EST = lubridate::interval(start = start_time_EST,
                                                      end = end_time_EST,
                                                      tz = "EST"),
         event_dur_sec = dseconds(datetime_interval_EST))
  
class(r2_events2$datetime_interval_EST)
tz(r2_events2$datetime_interval_EST) #timezone of interval gives an error
tz(r2_events2$start_time_EST) #timezone of start is EST
view(r2_events2)    

#To check the interval is in EST, we can pull out the start
start <- int_start( r2_events2$datetime_interval_EST[1])
class(start)
tz(start)

intervals <- r2_events2
#save
saveRDS(intervals, paste0(here, "/output/hobo_intervals.rds"))
rm(r2_events, r2_events2)
```


#3.0 filter hobo record based on event intervals
```{r}
hobo_all <- readRDS(paste0(here,"/output/hobo_compiled_wide.Rds"))


#create an empty dataframe with same headers
hobo_events <- slice(hobo_all, 0) 



for (i in 1:length(intervals$hobo_event_n)) {
  interval <- hobo_all %>%
    filter(dt %within% intervals$datetime_interval_EST[i]) %>% 
    mutate(hobo_event_n = intervals$hobo_event_n[i])
  
  hobo_events <- bind_rows(hobo_events, interval)
}

#Check timezone
tz(hobo_events$dt)
#Now the hourly time series record is filtered with event numbers

hobo_events2 <- hobo_events%>%
  pivot_longer(cols = contains("_mm"), names_to = "site", 
               values_to = "yield_mm")%>%
  group_by(site, dt) %>% 
  arrange(dt)%>% 
  mutate(site = case_when(site == "SFA_mm" ~ "SF-A",
                          site == "SFB_mm" ~ "SF-B",
                          site == "SFC_mm" ~ "SF-C",
                          site == "SFD_mm" ~ "SF-D",
                          site == "TFB_mm" ~ "TF-B",
                          site == "TFD_mm" ~ "TF-D"))%>%
  ungroup()%>% 
  select(dt, site,  yield_mm, hobo_event_n)%>%
  drop_na()



# 
 saveRDS(hobo_events2, paste0(here, "/output/hobo_events.Rds"))
```


#4.0 Create recession curve interval events
```{r}
hobo_events <- readRDS(paste0(here, "/output/hobo_events.Rds"))

curve_intervals <- read_csv(paste0(here, "/data/hobo_new_utf.csv"))
tz(curve_intervals$Start_dt_EST)
curve_intervals2 <- curve_intervals %>% 
  mutate(across(.cols = lubridate::is.POSIXct,
                ~ lubridate::force_tz(., tzone='EST'))) %>% 
  mutate(.after = End_dt_EST,
         datetime_interval_EST = lubridate::interval(start = Start_dt_EST,
                                                     end = End_dt_EST,
                                                     tz = "EST"),
         event_dur_sec = dseconds(datetime_interval_EST),
         event_dur_num = as.numeric(event_dur_sec))

write_csv(curve_intervals2,
          paste0(here,"/output/curve_intervals.csv"))



# tz(curve_intervals2$datetime_interval_EST)
sapply(curve_intervals2, class)

#Filter out multiple intervals 

#edit site ids to match
# hobo_events2 <- hobo_events %>%
#   mutate(site = case_when(site == "SFA_mm" ~ "SF-A",
#                           site == "SFB_mm" ~ "SF-B",
#                           site == "SFC_mm" ~ "SF-C",
#                           site == "SFD_mm" ~ "SF-D",
#                           site == "TFB_mm" ~ "TF-B",
#                           site == "TFD_mm" ~ "TF-D"))

#get list of site names to loop through
sites <- unique(curve_intervals2$site)

#create an empty dataframe with same headers
hobo_events_new <- slice(hobo_events, 0) 

#create a double loop to loop through sites and through curve intervals within each site
for(i in sites) {
 ts <- hobo_events %>% filter(site == i) #filter time series
 int <- curve_intervals2 %>% filter(site == i) #filter interval list
  for (j in 1:length(int$recession_n)) {
  interval <- ts %>%
    filter(dt %within% int$datetime_interval_EST[j]) %>% 
    mutate(recession_n = int$recession_n[j])
  
  hobo_events_new <- bind_rows(hobo_events_new, interval)
}
}
rm(ts, int, interval)
#Check and correct timezone
tz(hobo_events_new$dt)

#Save recession curve values
write_csv(hobo_events_new,
          paste0(here,"/output/rec_values.csv"))

```







